### ISSUE TITLE
Bug: jQuery Errors

### ISSUE THREAD

**Issue by dennis2menace** [melanietreitinger/block_eledia_adminexamdates#1]
On the homepage and the dashboard, we get the JS error "can´t find variable: jQuery". On course-sites we get 2 of them. 
The error is located in first.js and events.js under  
* @class Calendar ~jquery-calendar plugin~ (https://github.com/ArrobeFr/jquery-calendar-bs4)
 * @author Developped by Arrobe (https://www.arrobe.fr/)
 * Some Improvements, refactorizations and fixes: M. A. Coma Rivas
 * @license Licensed under MIT (https://github.com/ArrobeFr/jquery-calendar/blob/master/LICENSE)
 */
jQuery(document).ready((function($) {

There is no error on block examdate plugin pages.

We tried to fix it with 
            $PAGE->requires->jquery_plugin('ui');
inside the plugin, but learned, that the plugin uses its own jQuery instance.

**Is it necessary to "load" the plugin on every page?**

**Comment by melanietreitinger** [comment]
Which Moodle version are you using?

**Comment by dennis2menace** [comment]
Sorry. 4.1.7 and 4.1.9

**Comment by melanietreitinger** [comment]
And the error occurs in both versions?

**Comment by dennis2menace** [comment]
yes. You can have a look - the errors even occur on the login page.: https://pruefen.h-da.de/login/index.php
(on this server there´s block_eledia_adminexamdates V 03/23 running, the errors occur on our test-server running the version of this git, also)

**Comment by melanietreitinger** [comment]
Fixed in `v_41merge`.
